<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Nih</AssemblyName>
    <RootNamespace>Nih</RootNamespace>

    <!-- The example states its own attributes in Properties/AssemblyInfo. -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../../src/Boo.Lang/Boo.Lang.csproj" />
    <ProjectReference Include="../../../../../src/Boo.Lang.Compiler/Boo.Lang.Compiler.csproj" />
  </ItemGroup>

</Project>
