#region license
// Copyright (c) 2004, Rodrigo B. de Oliveira (rbo@acm.org)
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//     * Neither the name of Rodrigo B. de Oliveira nor the names of its
//     contributors may be used to endorse or promote products derived from this
//     software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#endregion

import System
import System.Linq.Enumerable
import System.IO
import Boo.Lang.Compiler
import Boo.Lang.Compiler.Pipelines
import Boo.Lang.Compiler.Ast
import Boo.Lang.Useful.BooTemplate from Boo.Lang.Useful

class Options:

	public static Language = "csharp"
	public static TemplateDir = "scripts/Templates"
	public static OutputDir = "src/Boo.Lang.Compiler/Ast"
	public static Extension = ".cs"


class Model:

	_module as Module

	def constructor([required] module as Module):
		self._module = module

	Members:
		get:
			return _module.Members

	def GetConcreteAstNodes():
		for member as TypeDefinition in Members:
			yield member if IsConcreteAstNode(member)

	def GetEnums():
		for member as TypeDefinition in Members:
			yield member if IsEnum(member)
			
	def IsNodeField(field as Field):
		if field.Type.ToString() == "Node": return true
		fieldType = ResolveFieldType(field)
		return fieldType is not null and not IsEnum(fieldType)

	def IsConcreteAstNode(member as TypeMember):
		return not (IsCollection(member) or IsEnum(member) or IsAbstract(member))

	def IsCollection(node as TypeMember):
		return node.Attributes.Contains("collection")

	def IsCollectionField(field as Field):
		return (field.Type as SimpleTypeReference).Name.EndsWith("Collection")

	def IsEnum(node as TypeMember):
		return NodeType.EnumDefinition == node.NodeType

	def IsAbstract(member as TypeMember):
		return member.IsModifierSet(TypeMemberModifiers.Abstract)

	def GetSimpleFields(node as ClassDefinition):
		return array(
			field
			for field as Field in node.Members
			unless IsCollectionField(field)
			or field.Attributes.Contains("auto"))

	def GetAllFields(node as ClassDefinition):
		fields = []
		for item as TypeDefinition in GetTypeHierarchy(node):
			fields.Extend(item.Members)
		return array(Field, fields)

	def IsVisitableField(field as Field):
		type = ResolveFieldType(field)
		return type is not null and not IsEnum(type)

	def GetVisitableFields(item as ClassDefinition):
		fields = []
		for item as TypeDefinition in GetTypeHierarchy(item):
			for field as Field in item.Members:
				fields.Add(field) if IsVisitableField(field)
		return array(Field, fields)

	def IsExpression(node as ClassDefinition):
		return IsSubclassOf(node, "Expression")

	def GetResultingTransformerNode(node as ClassDefinition):
		for subclass in ("Statement", "Expression", "TypeReference"):
			if IsSubclassOf(node, subclass):
				return subclass
		return node.Name

	def IsSubclassOf(node as ClassDefinition, typename as string) as bool:
		for typeref as SimpleTypeReference in node.BaseTypes:
			if typename == typeref.Name:
				return true
			baseType = node.DeclaringType.Members[typeref.Name]
			if baseType and IsSubclassOf(baseType, typename):
				return true
		return false

	def GetCollectionItemType(node as ClassDefinition):
		attribute = node.Attributes.Get("collection").First()
		reference as ReferenceExpression = attribute.Arguments[0]
		return reference.Name

	def ResolveFieldType(field as Field):
		return _module.Members[(field.Type as SimpleTypeReference).Name]


class CodeTemplate(AbstractTemplate):

	static header = (
"""${read('notice.txt')}
//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by astgen.boo.
//
""")

	[property(model)]
	_model as Model

	[property(node)]
	_node as TypeDefinition

	def GetPrivateName(field as Field):
		name = field.Name
		return "_" + name[0:1].ToLower() + name[1:]

	def FormatParameterList(fields):
		return join(
			"${field.Type} ${GetParameterName(field)}"
			for field as Field in fields,
			", ")

	def GetParameterName(field as Field):
		name = field.Name
		name = name[0:1].ToLower() + name[1:]
		if name in ("namespace", "operator"):
			return "@" + name
		return name

def read(fname as string):
	using reader=File.OpenText(fname):
		return reader.ReadToEnd()

def GetPath(fname as string):
	return Path.Combine(Options.OutputDir, fname)

def GetTypeHierarchy(item as ClassDefinition):
	types = []
	ProcessTypeHierarchy(types, item)
	return types

def ProcessTypeHierarchy(types as List, item as ClassDefinition):
	module as Module = item.ParentNode
	for baseTypeRef as SimpleTypeReference in item.BaseTypes:
		if baseType = module.Members[baseTypeRef.Name]:
			ProcessTypeHierarchy(types, baseType)
	types.Add(item)

def parse(fname):
	compiler = BooCompiler()
	compiler.Parameters.Pipeline = Parse()
	compiler.Parameters.Input.Add(Boo.Lang.Compiler.IO.FileInput(fname))
	result = compiler.Run()
	assert 0 == len(result.Errors), result.Errors.ToString()
	return result.CompileUnit.Modules[0]

def loadTemplate(model, fname as string):
	compiler = TemplateCompiler(TemplateBaseClass: CodeTemplate)
	compiler.DefaultImports.Add("Boo.Lang.Compiler.Ast")
	result = compiler.CompileFile(Path.Combine(Options.TemplateDir, fname + Options.Extension))
	assert 0 == len(result.Errors), result.Errors.ToString()

	templateType = result.GeneratedAssembly.GetType("Template")
	template as CodeTemplate = templateType()
	template.model = model
	return template

def applyTemplate(node as TypeDefinition,
			template as CodeTemplate,
			targetFile as string,
			overwriteExistingFile as bool):

	fname = GetPath(targetFile + Options.Extension)
	if not overwriteExistingFile:
		return if File.Exists(fname) or File.Exists(fname.Replace(".Generated", ""))

	print targetFile
	using writer=StreamWriter(fname):
		template.node = node
		template.Output = writer
		template.Execute()

def applyModelTemplate(model as Model, templateName as string, targetFile as string, overwriteExistingFile as bool):
	applyTemplate(null, loadTemplate(model, templateName), targetFile, overwriteExistingFile)

for arg in argv:
	if arg.StartsWith("--language="):
		Options.Language = arg.Substring("--language=".Length)
	elif arg.StartsWith("--out="):
		Options.OutputDir = arg.Substring("--out=".Length)

if Options.Language == "boo":
	Options.TemplateDir = Path.Combine(Options.TemplateDir, "Boo")
	Options.Extension = ".boo"
elif Options.Language != "csharp":
	print "astgen: unknown language '${Options.Language}', expected csharp or boo"
	Environment.Exit(1)

start = date.Now

model = Model(parse("ast.model.boo"))

if Options.Language == "boo":
	# Only the templates whose output stands on its own are retargeted so far.
	# The rest generate one half of a partial class whose other half is still
	# hand written C#, and a partial class cannot span languages.
	applyModelTemplate(model, "NodeType", "NodeType.Generated", true)

	enumTemplate = loadTemplate(model, "Enum")
	for member in model.Members:
		continue if member.Attributes.Contains("ignore")
		applyTemplate(member, enumTemplate, "${member.Name}.Generated", true) if model.IsEnum(member)
else:
	applyModelTemplate(model, "IAstVisitor", "IAstVisitor.Generated", true)
	applyModelTemplate(model, "DepthFirstGuide", "Impl/DepthFirstGuide", true)
	applyModelTemplate(model, "DepthFirstVisitor", "Impl/DepthFirstVisitor", true)
	applyModelTemplate(model, "FastDepthFirstVisitor", "Impl/FastDepthFirstVisitor", true)
	applyModelTemplate(model, "DepthFirstTransformer", "Impl/DepthFirstTransformer", true)
	applyModelTemplate(model, "CodeSerializer", "Impl/CodeSerializer", true)
	applyModelTemplate(model, "NodeType", "NodeType.Generated", true)

	enumTemplate = loadTemplate(model, "Enum")
	collectionTemplate = loadTemplate(model, "Collection")
	collectionImplTemplate = loadTemplate(model, "CollectionImpl")
	nodeTemplate = loadTemplate(model, "Node")
	nodeImplTemplate = loadTemplate(model, "NodeImpl")

	for member in model.Members:
		continue if member.Attributes.Contains("ignore")

		if model.IsEnum(member):
			applyTemplate(member, enumTemplate, "${member.Name}.Generated", true)
		elif model.IsCollection(member):
			applyTemplate(member, collectionTemplate, "${member.Name}.Generated", false)
			applyTemplate(member, collectionImplTemplate, "Impl/${member.Name}Impl", true)
		else:
			applyTemplate(member, nodeTemplate, "${member.Name}.Generated", false)
			applyTemplate(member, nodeImplTemplate, "Impl/${member.Name}Impl", true)

stop = date.Now
print "ast classes generated in ${stop-start}."

