<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Boo.Lang.Compiler</AssemblyName>
    <RootNamespace>Boo.Lang.Compiler</RootNamespace>
    <Description>Boo compiler pipeline, type system and code generator.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Boo.Lang/Boo.Lang.csproj" />
  </ItemGroup>

</Project>
