<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>boo</string>
	</array>
	<key>name</key>
	<string>Boo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#definitions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macros</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtins</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invocations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.boo</string>
					<key>match</key>
					<string>#.*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.boo</string>
					<key>match</key>
					<string>//.*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block.boo</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.boo</string>
					<key>begin</key>
					<string>"""</string>
					<key>end</key>
					<string>"""</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.boo</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.boo</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
						<dict>
							<key>name</key>
							<string>meta.embedded.boo</string>
							<key>begin</key>
							<string>\$\{</string>
							<key>end</key>
							<string>\}</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.single.boo</string>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.boo</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>string.regexp.boo</string>
					<key>match</key>
					<string>@/(\\.|[^/])*/</string>
				</dict>
			</array>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.attribute.boo</string>
					<key>match</key>
					<string>(\[)(assembly|module)(:)\s*([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.attribute-specifier.boo</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.attribute.boo</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.attribute.boo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.attribute.boo</string>
					<key>match</key>
					<string>^\s*(\[)\s*([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)(?=\s*[(,\]])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.attribute.boo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(assert|case|checked|debug|ifdef|initialization|lock|match|normalArrayIndexing|order|otherwise|preserving|preservingLexicalInfo|print|property|rawArrayIndexing|unchecked|unsafe|using|var|yieldAll)\b(?=\s|:|\(|$)(?!\s*=[^=])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.macro.boo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>invocations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:(\.)\s*)?([A-Za-z_][A-Za-z0-9_]*)(?=\s*(?:\[of\b(?:[^\[\]]|\[[^\]]*\])*\])?\s*\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.boo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>([A-Za-z_][A-Za-z0-9_]*)(?=\s*\.\s*[A-Za-z_])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.object.boo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.)\s*([A-Za-z_][A-Za-z0-9_]*)(?![A-Za-z0-9_]|\s*\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.accessor.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.object.property.boo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.boo</string>
					<key>match</key>
					<string>\b(break|continue|do|elif|else|end|ensure|except|failure|for|goto|if|in|raise|return|then|try|unless|while|yield|pass)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.other.boo</string>
					<key>match</key>
					<string>\b(and|as|cast|from|import|is|isa|namespace|new|not|of|or|typeof)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.type.boo</string>
					<key>match</key>
					<string>\b(class|constructor|def|destructor|enum|event|interface|struct)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>storage.modifier.boo</string>
					<key>match</key>
					<string>\b(abstract|final|get|internal|override|partial|private|protected|public|ref|set|static|transient|virtual)\b</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.true.boo</string>
					<key>match</key>
					<string>\btrue\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.boolean.false.boo</string>
					<key>match</key>
					<string>\bfalse\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.null.boo</string>
					<key>match</key>
					<string>\bnull\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.self.boo</string>
					<key>match</key>
					<string>\bself\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.language.super.boo</string>
					<key>match</key>
					<string>\bsuper\b</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.boo</string>
					<key>match</key>
					<string>\b0[xX][0-9a-fA-F]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.boo</string>
					<key>match</key>
					<string>\b[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?[lLfFdDmM]?\b</string>
				</dict>
			</array>
		</dict>
		<key>definitions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(def|constructor)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.boo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*(macro)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.macro.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.macro.boo</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(class|struct|interface|enum)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.boo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.boo</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.type.primitive.boo</string>
					<key>match</key>
					<string>\b(bool|byte|callable|char|date|decimal|double|duck|int|long|object|regex|sbyte|short|single|string|timespan|uint|ulong|ushort|void)\b</string>
				</dict>
			</array>
		</dict>
		<key>builtins</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.boo</string>
					<key>match</key>
					<string>(?&lt;!\.)\b(array|cat|enumerate|gets|iterator|join|len|map|matrix|print|prompt|quack|range|reversed|shell|shellp|zip)\b(?=\s*\()</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.boo</string>
					<key>match</key>
					<string>\b(__addressof__|__default__|__initobj__|__switch__)\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.boo</string>
					<key>match</key>
					<string>\*\*|&lt;&lt;=|&gt;&gt;=|&lt;&lt;|&gt;&gt;|&lt;=|&gt;=|==|!=|!~|=~|\+\+|--|[+\-*/%&amp;|^]=|=|[+\-*/%&amp;|^~&lt;&gt;]</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.boo</string>
	<key>uuid</key>
	<string>8224EC55-DEF6-5E55-9C3F-4D0FE6638AAA</string>
</dict>
</plist>
